### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by uberspeck** [cstefanache/ng2-components#1]
I just forked the repo and I'm getting the following npm error. My intent was to upgrade to RC4 and do a pull request. I'm on OS X and running `node v4.4.7` and `npm v3.10.5`

```console
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! ng2-component@0.3.7 prepublish: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ng2-component@0.3.7 prepublish script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-component package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-component
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-component
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/brian/dev/ng2-components/npm-debug.log
```

**Comment by cstefanache** [comment]
Do you have typescript installed globally?

**Comment by uberspeck** [comment]
Yup! `v1.8.10`

**Comment by uberspeck** [comment]
FYI, here's the tail of `npm-debug.log`...

```console
48324 verbose lifecycle ng2-component@0.3.7~prepublish: unsafe-perm in lifecycle true
48325 verbose lifecycle ng2-component@0.3.7~prepublish: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/brian/dev/ng2-components/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/Ghostscript/bin:/usr/local/git/bin:/opt/ImageMagick/bin:/usr/local/mongodb/bin:/usr/local/mysql/bin:/usr/local/Cellar/mongodb/3.0.2//bin
48326 verbose lifecycle ng2-component@0.3.7~prepublish: CWD: /Users/brian/dev/ng2-components
48327 silly lifecycle ng2-component@0.3.7~prepublish: Args: [ '-c', 'tsc' ]
48328 silly lifecycle ng2-component@0.3.7~prepublish: Returned: code: 2  signal: null
48329 info lifecycle ng2-component@0.3.7~prepublish: Failed to exec prepublish script
48330 verbose stack Error: ng2-component@0.3.7 prepublish: `tsc`
48330 verbose stack Exit status 2
48330 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
48330 verbose stack     at emitTwo (events.js:87:13)
48330 verbose stack     at EventEmitter.emit (events.js:172:7)
48330 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
48330 verbose stack     at emitTwo (events.js:87:13)
48330 verbose stack     at ChildProcess.emit (events.js:172:7)
48330 verbose stack     at maybeClose (internal/child_process.js:827:16)
48330 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
48331 verbose pkgid ng2-component@0.3.7
48332 verbose cwd /Users/brian/dev/ng2-components
48333 error Darwin 15.6.0
48334 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
48335 error node v4.4.7
48336 error npm  v3.10.5
48337 error code ELIFECYCLE
48338 error ng2-component@0.3.7 prepublish: `tsc`
48338 error Exit status 2
48339 error Failed at the ng2-component@0.3.7 prepublish script 'tsc'.
48339 error Make sure you have the latest version of node.js and npm installed.
48339 error If you do, this is most likely a problem with the ng2-component package,
48339 error not with npm itself.
48339 error Tell the author that this fails on your system:
48339 error     tsc
48339 error You can get information on how to open an issue for this project with:
48339 error     npm bugs ng2-component
48339 error Or if that isn't available, you can get their info via:
48339 error     npm owner ls ng2-component
48339 error There is likely additional logging output above.
48340 verbose exit [ 1, true ]
```

**Comment by uberspeck** [comment]
Ok, i added `"postinstall": "typings install"` to `scripts` in `package.json` and that seems to have fixed the issue
